name: memo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^3.2.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  ionicons: ^0.2.2
  iconify_flutter: ^0.0.5
  window_to_front: ^0.0.3
  url_launcher: ^6.1.7
  oauth2: ^2.0.1
  build_runner: ^2.4.11
  firebase_database: ^11.0.4
  flutter_animate: ^4.5.0
  auto_size_text: ^3.0.0
  linked_scroll_controller: ^0.2.0
  cached_network_image: ^3.4.0
  flutter_staggered_grid_view: ^0.7.0
  popup_menu: ^2.0.0
  popup_menu_plus: ^0.0.6
  http: ^1.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_rename_app_plus3: ^1.2.3
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2
  rename_app: ^1.6.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_rename_app_plus3:
  application_name: Memo
  dart_package_name: memo
  application_id: com.android.memo
  bundle_id: com.ios.memo
  ios_bundle_name: Memo

flutter:

  uses-material-design: true


