// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1Zv6mrY85VtpEWjmyG5PrWGv-eT9uU8',
    appId: '1:767054581067:android:d64d356adb8c2ea8b0acce',
    messagingSenderId: '767054581067',
    projectId: 'memomind-7b0a4',
    storageBucket: 'memomind-7b0a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTzvs-IgGa7Ldhkhl0tqtb7bsZIOJ84M',
    appId: '1:767054581067:ios:643b226cb6ecbef3b0acce',
    messagingSenderId: '767054581067',
    projectId: 'memomind-7b0a4',
    storageBucket: 'memomind-7b0a4.appspot.com',
    iosClientId: '767054581067-b3s5fmoljv4qltu6qftte7kr9nlijsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTzvs-IgGa7Ldhkhl0tqtb7bsZIOJ84M',
    appId: '1:767054581067:ios:643b226cb6ecbef3b0acce',
    messagingSenderId: '767054581067',
    projectId: 'memomind-7b0a4',
    storageBucket: 'memomind-7b0a4.appspot.com',
    iosClientId: '767054581067-b3s5fmoljv4qltu6qftte7kr9nlijsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZJqspFIOnas6H1Z26UcedeQz7xq_nJ4',
    appId: '1:767054581067:web:cc9c1e19f72832f2b0acce',
    messagingSenderId: '767054581067',
    projectId: 'memomind-7b0a4',
    authDomain: 'memomind-7b0a4.firebaseapp.com',
    storageBucket: 'memomind-7b0a4.appspot.com',
  );

}